FROM astral/uv:python3.13-bookworm
WORKDIR /app

# Put the pyproject.toml & print_date.py file into the container
COPY pyproject.toml .
COPY print_date.py .

# Create a virtual environment and set the location to /app/.venv
RUN uv venv
# Install the dependencies
RUN uv sync

CMD ["uv", "run", "python", "print_date.py"]